### ISSUE TITLE
TypeError: Image or Canvas expected

### ISSUE THREAD

**Issue by TheMonDon** [flazepe/node-canvas-with-twemoji-and-discord-emoji#2]
I get this error when trying to send the canvas to discord as an attachment:
`(node:23382) UnhandledPromiseRejectionWarning: TypeError: Image or Canvas expected
    at drawTextWithEmoji (/home/john/discord/CISN/main/node_modules/node-canvas-with-twemoji-and-discord-emoji/src/drawTextWithTwemoji.js:65:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async exports.fillTextWithTwemoji (/home/john/discord/CISN/main/node_modules/node-canvas-with-twemoji-and-discord-emoji/src/index.js:5:10)
    at async main (eval at <anonymous> (eval at Actions.eval (/home/john/discord/CISN/main/bot.js:344:10)), <anonymous>:10:2)
(node:23382) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:23382) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Here is the code (mostly the example): 
https://pastebin.com/DS1wKUT1

**Comment by HarukaYamamoto0** [comment]
look, I know this question was 1 year ago, but I'll still answer:

1st you are required to put the name of the attachment when it is sent

2nd you tried to create an attachment, but you didn't export the discord.js module
